### ISSUE TITLE
LMC CR

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/LMC-TS#11]
**TASK OWNER: SKL,RAJA & SQL TEAM**

TARGET DATE:20/04/2015

add these(Drive URL fr screenshots) values in DB nd make it as a DD box in the FORM fr these PARTS oly, also add possibility to update or add more values in SETTINGS PAGE:

https://drive.google.com/a/ssomens.com/file/d/0B0KangOyYg_pTG9IdWxlNDFkeTNLQW16ZWNpZFZNdFNPdEs4/view

https://drive.google.com/a/ssomens.com/file/d/0B0KangOyYg_pVEQ4NHMyQXpYTG81YldRbmdwQXhMbzdrSUNn/view

1. MACHINERY/EQUIPMENT TRANSFER
2.  MACHINERY USAGE
3. FITTINGS USAGE
4. MATERIAL USAGE

Contract no also will be a DD box now. We ll get form DB.
They ll even create a contract using Form. tht no. ll show in the DD in the form!
"

**Comment by DHANDAPANISATTANATHAN** [comment]
PAINT TOOL HAS ISSUE FIX AND DELY

**Comment by punithavimalraj** [comment]
PAINT ISSUE FIXED

https://github.com/SSOMENSREPO/LMC-TS/releases/tag/v0.7
