### ISSUE TITLE
LMC ISSUE NOT SHOW ERR MSG

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/LMC-TS#12]
**SKL & RAJA,**

**DEFECT OWNER: SKL**

Defect opened to sql team.Check below.but while testing why u didnt show err msg. Nothing showed.Also report preloader not disappear bcz of below issue

https://github.com/SSOMENSREPO/LMC-TS-SQL/issues/1

**Comment by SasikalaDjeasankar** [comment]
SHOWED ERROR MESSAGE WHEN QUERY RETURNS ERROR, UPDATED THE SCRIPT IN REMOTE SERVER.

FILENAME: FORM_CONFIGURATION_ENTRY.php
