### ISSUE TITLE
LMC ISSUE IN REPORT

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/LMC-TS#13]
**DEFECT OWNER: SKL
TASK OWNER:RAJA**

1.if TOOLBOX MEETING - REMARKS  not entered report not saved
2.Remove the paint tool mandatory * from form.
3.If JOB DONE pipe laid M / MM, if M entered MM not entered report not saved.

Clear these issue and dely before 11 am 23/04/2015

**Comment by Rajagunasekaran** [comment]
Above opened issues are fixed
