### ISSUE TITLE
LMC DEFECT ON 29032016 

### ISSUE THREAD

**Issue by mugilansoft** [SSOMENSREPO/LMC-TS#29]
@BalachandarNatarajan 
IN INVENTORY SYSTEM MENU INVENTORY LIST ENTRY / UPDATE FORM  D T SHOWING WHITE SPACE
![issuse17](https://cloud.githubusercontent.com/assets/16263469/14104269/edf3f3fe-f5c1-11e5-8d0f-88e92dc23fe6.png)

**Comment by sophiyaB** [comment]
@RAJALAKSHMIRAJKUMAR 

IN PROJECT CHART FORM THE PROJECT TIMELINE AND UPDATE TIMELINE OVERLAPPING 
BECAUSE OF END DATE NULL SO QUERY WANT TO CHANGE .

**Comment by mugilansoft** [comment]
@SasikalaDjeasankar 
IN REPORT SUBMISSION MENU VERIFICATION OF WORK DONE FORM
![issue18](https://cloud.githubusercontent.com/assets/16263469/14109844/9c1dc4ea-f5e1-11e5-8600-ae08262a4336.png)

**Comment by SasikalaDjeasankar** [comment]
@RAJALAKSHMIRAJKUMAR 

While saving verification of workdone, success flag returning 0 but main table record saved so we are getting issue in payment claim form.

**Comment by RAJALAKSHMIRAJKUMAR** [comment]
Verification of work done form owner need to pass id for item.

**Comment by BalachandarNatarajan** [comment]
IN PAYMENT CLAIM FITTING REPORT,QUANTITY MUST BE THE NUMBER OF ITEMS USED IN VERIFICATION OF WORK DONE AND THE AMOUNT MUST BE THE MULTIPLE OF QUANTITY AND SUPPLIER PRICE.

**Comment by KAVINKARNAN** [comment]
Issue no #30  Fixed all 
### Status :closed
